#Dockerfile

# prepaire evn
FROM ruby:3.1.2

RUN apt-get update -qq && apt-get install -y build-essential

RUN mkdir /intern-be-2022
WORKDIR /intern-be-2022

COPY Gemfile* ./
RUN bundle install

COPY . ./
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]  
