FROM node:18.12.0-alpine3.16

RUN mkdir /intern-fe-2022

WORKDIR /intern-fe-2022

COPY package*.json /intern-fe-2022

COPY yarn.lock /intern-fe-2022

RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*

RUN yarn install

COPY . /intern-fe-2022

CMD [ "yarn","start:dev" ]
